networks:
  default:
    driver: bridge
    name: roboshop
    #external: true #I created network already using docker network create roboshop

services:
  mongodb:
    image: 9eguru/mongodb:v1
    container_name: mongodb
    
  catalogue:
    image: 9eguru/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
    
  user:
    image: 9eguru/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: 9eguru/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: 9eguru/mysql:v1
    container_name: mysql
    
  shipping:
    image: 9eguru/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
